### ISSUE TITLE
Cleanup repo + readme + dev env

### ISSUE THREAD

**Issue by mbianchidev** [mbianchidev/klab-cli#26]
```[tasklist]
### Tasks
- [x] Crate readme doc
- [x] Cleanup repo from unused stuff like template-generator.py
- [x] Understand the best structure for the repo since now it's just Terraform with main.tf file
- [x] APIs (different repo for APIs?)
- [x] frontend (different repo for frontend?)
- [x] Write in the readme the pre-requirements for installing lab CLI such as awscli, azurecli, kubectl, terraform, python, bash -c "$(curl -sSL https://install.mondoo.com/sh)" etc.
- [x] Remove Jinja and other from requirements.txt (not needed)
- [x] Add a linter / automatic formatting for python using rules that make sense
- [x] Provide a bash script to install everything needed to run lab as kubelab-install.sh
- [x] Move everything from kubelab-cli to the root folder
- [x] Setup devcontainer (Kind + Terraform + something else) on VSCode - see if feasible/doable
- [ ] Documentaton for dev environment setup https://kind.sigs.k8s.io/docs/user/quick-start/ on readme
- [x] Create contribute.md for contribution guidelines
- [x] Setup pypi package https://medium.com/@joel.barmettler/how-to-upload-your-python-package-to-pypi-65edc5fe9c56
- [x] Make the tests run only on main and at night? (github workflow) - 10 minutes of timeout due to lab create is too much
- [ ] https://github.com/KubeLab-cloud/kubelab-middleware/issues/93
```
